import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Case", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("property_address", models.CharField(max_length=255)), ("landlord_or_manager", models.CharField(blank=True, max_length=160)), ("move_in_date", models.DateField(blank=True, null=True)), ("summary", models.TextField(blank=True)), ("status", models.CharField(choices=[("active", "Active"), ("resolved", "Resolved"), ("archived", "Archived")], default="active", max_length=20)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="housing_cases", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-updated_at"]}),
        migrations.CreateModel(name="Incident", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("category", models.CharField(choices=[("repair", "Repair or maintenance"), ("communication", "Communication"), ("inspection", "Inspection or entry"), ("notice", "Notice received or sent"), ("payment", "Rent or payment"), ("other", "Other")], max_length=30)), ("occurred_at", models.DateTimeField()), ("description", models.TextField()), ("people_involved", models.CharField(blank=True, max_length=255)), ("created_at", models.DateTimeField(auto_now_add=True)), ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incidents", to="core.case"))], options={"ordering": ["-occurred_at"]}),
        migrations.CreateModel(name="Evidence", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("evidence_type", models.CharField(choices=[("photo", "Photo"), ("video", "Video"), ("audio", "Audio"), ("message", "Message or email"), ("notice", "Notice or letter"), ("report", "Inspection or contractor report"), ("receipt", "Receipt or payment record"), ("other", "Other")], max_length=30)), ("file", models.FileField(upload_to="evidence/%Y/%m/")), ("notes", models.TextField(blank=True)), ("uploaded_at", models.DateTimeField(auto_now_add=True)), ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence", to="core.case")), ("incident", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="evidence", to="core.incident"))], options={"ordering": ["-uploaded_at"]}),
    ]
